services:
  expense-tracker-app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=expense_tracker_1
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
