spring.application.name=expense_app
server.port=8081

spring.datasource.url=jdbc:mysql://mysql-db:3306/expense_tracker_1
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
logging.level.org.springframework.security=TRACE
